version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "25039:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "25040:5000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=http://localhost:25040

networks:
  app-network:
    driver: bridge